version: "3.8"
services:
  db:
    image: postgres:16
    container_name: db
    env_file:
      - .env
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: hakaton_ai
    depends_on:
      - db